services:
  - type: web
    name: gold-png-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        scope: runtime
      - key: NODE_ENV
        value: production

cronjobs:
  - name: gold-rate-fetcher
    runtime: node
    schedule: "*/15 3-15 * * *"
    command: npm run cron
    envVars:
      - key: MONGO_URI
        scope: runtime
      - key: NODE_ENV
        value: production
